"""Job offers

Revision ID: 1f6d8266ae60
Revises: 
Create Date: 2023-05-20 18:42:25.748150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f6d8266ae60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('joboffer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('positives', sa.String(), nullable=False),
    sa.Column('negatives', sa.String(), nullable=False),
    sa.Column('positive_keywords', sa.String(), nullable=False),
    sa.Column('negative_keywords', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('email_text', sa.String(), nullable=False),
    sa.Column('website_copy', sa.LargeBinary(), nullable=True),
    sa.Column('assigned_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_joboffer_id'), 'joboffer', ['id'], unique=False)
    op.create_index(op.f('ix_joboffer_provider'), 'joboffer', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('joboffer')
